linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.7"
   services:
     - docker
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/gcc7

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
